/* eslint-disable prettier/prettier */
import { Seed } from '@core/sql/seeder/seeder.dto';
import { Setting } from '../../modules/sql/setting/entities/setting.entity';

export default <Seed<Setting>>{
  model: 'Setting',
  action: 'once',
  data: [
    {
      name: 'contact_us',
      display_name: 'Contact Email',
      value: 'contact_us@mailinator.com',
      group_id: 1,
      option: {
        type: 'email',
        format: 'email',
        required: true,
      },
    },
    {
      name: 'customer_service_email',
      display_name: 'Customer Service Email',
      value: 'contact_us@mailinator.com',
      group_id: 1,
      option: {
        type: 'email',
        format: 'email',
        required: true,
      },
    },
    {
      name: 'order_service_email',
      display_name: 'Order Service Email',
      value: 'contact_us@mailinator.com',
      group_id: 1,
      option: {
        type: 'email',
        format: 'email',
        required: true,
      },
    },
    {
      name: 'shipping_limit',
      display_name: 'Free shipping limit',
      value: '70.00',
      group_id: 1,
      option: {
        type: 'number',
        format: 'amount',
        required: true,
        min: 0,
      },
    },
    {
      name: 'commission',
      display_name: 'Commission',
      value: '25',
      group_id: 1,
      option: {
        type: 'number',
        format: 'amount',
        required: true,
        min: 0,
      },
    },
    {
      name: 'minus_price',
      display_name: 'Minus Price (Shipping)',
      value: '25',
      group_id: 1,
      option: {
        type: 'number',
        format: 'amount',
        required: true,
        min: 0,
      },
    },
    {
      name: 'shipping_price',
      display_name: 'Shipping Price',
      value: '25',
      group_id: 1,
      option: {
        type: 'number',
        format: 'amount',
        required: true,
        min: 0,
      },
    },
    {
      name: 'tax',
      display_name: 'Tax',
      value: '10',
      group_id: 1,
      option: {
        type: 'number',
        format: 'amount',
        required: true,
        min: 0,
      },
    },
    {
      name: 'hours_for_cancellation',
      display_name: 'Hours for Cancellation',
      value: '24',
      group_id: 1,
      option: {
        type: 'number',
        format: 'amount',
        required: true,
        min: 0,
      },
    },
    {
      name: 'timer_for_final_reminder',
      display_name: 'Timer for Final Reminder',
      value: '22',
      group_id: 1,
      option: {
        type: 'number',
        format: 'amount',
        required: true,
        min: 0,
      },
    },
    {
      name: 'xps_sender_address_name',
      display_name: 'Name',
      value: 'Orders',
      group_id: 2,
      option: {
        type: 'text',
        format: 'amount',
        required: true,
        min: 0,
      },
    },
    {
      name: 'xps_sender_company_name',
      display_name: 'Company',
      value: 'OPUS',
      group_id: 2,
      option: {
        type: 'text',
        format: 'amount',
        required: true,
        min: 0,
      },
    },
    {
      name: 'xps_sender_address_zip',
      display_name: 'Zip',
      value: '07463',
      group_id: 2,
      option: {
        type: 'text',
        format: 'amount',
        required: true,
        min: 0,
      },
    },
    {
      name: 'xps_sender_address_state',
      display_name: 'State',
      value: 'NJ',
      group_id: 2,
      option: {
        type: 'text',
        format: 'amount',
        required: true,
        min: 0,
      },
    },
    {
      name: 'xps_sender_address_city',
      display_name: 'City',
      value: 'Waldwick',
      group_id: 2,
      option: {
        type: 'text',
        format: 'amount',
        required: true,
        min: 0,
      },
    },
    {
      name: 'xps_sender_address_address1',
      display_name: 'Address1',
      value: '401 N Middletown Road',
      group_id: 2,
      option: {
        type: 'text',
        format: 'amount',
        required: true,
        min: 0,
      },
    },
    {
      name: 'xps_sender_address_address2',
      display_name: 'Address2',
      value: 'Pearl River',
      group_id: 2,
      option: {
        type: 'text',
        format: 'amount',
        required: true,
        min: 0,
      },
    },
    {
      name: 'xps_sender_address_email',
      display_name: 'Email',
      value: 'orders@physiciansonlycbd.com',
      group_id: 2,
      option: {
        type: 'text',
        format: 'amount',
        required: true,
        min: 0,
      },
    },
    {
      name: 'xps_sender_address_phone',
      display_name: 'Phone',
      value: '9143702300',
      group_id: 2,
      option: {
        type: 'text',
        format: 'amount',
        required: true,
        min: 0,
      },
    },
    {
      name: 'xps_sender_address_country',
      display_name: 'Country',
      value: 'US',
      group_id: 2,
      option: {
        type: 'text',
        format: 'amount',
        required: true,
        min: 0,
      },
    },
    {
      name: 'xps_return_address_name',
      display_name: 'Name',
      value: 'Orders',
      group_id: 3,
      option: {
        type: 'text',
        format: 'amount',
        required: true,
        min: 0,
      },
    },
    {
      name: 'xps_return_company_name',
      display_name: 'Company',
      value: 'OPUS',
      group_id: 2,
      option: {
        type: 'text',
        format: 'amount',
        required: true,
        min: 0,
      },
    },
    {
      name: 'xps_return_address_zip',
      display_name: 'Zip',
      value: '07463',
      group_id: 3,
      option: {
        type: 'text',
        format: 'amount',
        required: true,
        min: 0,
      },
    },
    {
      name: 'xps_return_address_state',
      display_name: 'State',
      value: 'NJ',
      group_id: 3,
      option: {
        type: 'text',
        format: 'amount',
        required: true,
        min: 0,
      },
    },
    {
      name: 'xps_return_address_city',
      display_name: 'City',
      value: 'Waldwick',
      group_id: 3,
      option: {
        type: 'text',
        format: 'amount',
        required: true,
        min: 0,
      },
    },
    {
      name: 'xps_return_address_address1',
      display_name: 'Address1',
      value: '401 N Middletown Road',
      group_id: 3,
      option: {
        type: 'text',
        format: 'amount',
        required: true,
        min: 0,
      },
    },
    {
      name: 'xps_return_address_address2',
      display_name: 'Address2',
      value: 'Pearl River',
      group_id: 3,
      option: {
        type: 'text',
        format: 'amount',
        required: true,
        min: 0,
      },
    },
    {
      name: 'xps_return_address_email',
      display_name: 'Email',
      value: 'orders@physiciansonlycbd.com',
      group_id: 3,
      option: {
        type: 'text',
        format: 'amount',
        required: true,
        min: 0,
      },
    },
    {
      name: 'xps_return_address_phone',
      display_name: 'Phone',
      value: '9143702300',
      group_id: 3,
      option: {
        type: 'text',
        format: 'amount',
        required: true,
        min: 0,
      },
    },
    {
      name: 'xps_return_address_country',
      display_name: 'Country',
      value: 'US',
      group_id: 3,
      option: {
        type: 'text',
        format: 'amount',
        required: true,
        min: 0,
      },
    },
  ],
};
